# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Massolit Media Technical Writing Services
email: massolit.media@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A collection of technical writing samples by me, Philip Tanfield, that demonstrate my expertise around creating technical content related to information technology, information security, and more.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tech-writer.massolit-media.com" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
theme: just-the-docs
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Custom SASS/CSS
sass:
  sass_dir: _sass
  style: compressed

# Permalinks
# permalink: pretty
# permalink: /:title:/

# Collections
collections:
  learning-jekyll:
    output: true
    permalink: /tutorials/learning-jekyll/:name/
  security-onion-series-win11-2026:
    output: true
    permalink: /tutorials/security-onion-series-win11-2026/:name/
  security-onion-series-macos-2022:
    output: true
    permalink: /tutorials/security-onion-series-macos-2022/:name/


# Display Collections in Sidebar nav:
just_the_docs:
  collections:
    learning-jekyll:
      name: Learning Jekyll
    security-onion-series-win11-2026:
      name: Security Onion Series (Windows 11, 2026)
    security-onion-series-macos-2022:
      name: Security Onion Series (MacOS, 2022)

# Additional In-page Navigation (https://just-the-docs.com/docs/navigation/in-page/)
back_to_top: true
back_to_top_text: "Back to top"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Google Analytics Tracking (2022-09-04)
# I got it from the Just the docs documentation and am leaving the anonymize_ip and comment the way it was there.
# I tried using the Massolit-Media.com property but eventually set up a separate GA property.
ga_tracking: G-QBG3F9C10M # Massolit Media - Google Analytics 4 Measurement ID - added under my own initiative
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)

# Styling Callouts (2026-06-05)
# https://just-the-docs.com/docs/ui-components/callouts/
callouts:
  highlight:
    title: highlight
    color: yellow
  note:
    title: Note
    color: yellow
  warning:
    title: Warning
    color: red
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
