version: 0.2

phases:
  install:
    runtime-versions:
      ruby: latest
    commands:
      - ruby -v
      - gem install bundler -v 4.0.12
      - rm -rf _site
      - bundle install

  build:
    commands:
      - echo "******** Building Jekyll site ********"
      - bundle exec jekyll build
      - echo "******** Uploading to S3 ********"
      - aws s3 sync _site/ s3://tech-writer.massolit-media.com --delete
      - aws cloudfront create-invalidation --distribution-id EODEMCA6K6NC4 --paths '/*'